[System]
MultipleLaunch	= 0
FullScreenInit	= 0
Language	= Default
VSYNC		= 1
EnableBlackoutShortcut = 1
EnableShader	= 1


[Network]
NetworkMode	= 0
Controler	= 0
Port		= 50004
ServersDatFileName = servers.dat
SyncColors	= 1


[Configuration]
ScreenZ		= 217.3
ScreenW		= 180.0
ObjZ		= 400.0
NearZ		= 30.0
MidZ		= 25000.0
FarZ		= 2000000000.0
;OverlapZ	= 500.0
OverlapZ	= 0.0
EyeRole		= C
EyeDist		= 6.4
EnableChangeEyeDist = 1
TitleWidthRatio	= 1.0
FadeAngleFactor	= 1.0


[Window]
WinX		= 0
WinY		= 0
WinW		= 1280
WinH		= 720
MgnW		= 0
MgnH		= 0


[Directory]
Data		= ./data/
Programs	= ./programs/
Locale		= ./locale/
Textures	= ./textures/
Media		= ./media/
Spacecraft	= ./spacecraft/
Skyline		= ./skyline/


[WindowConfigFile]
WindowMode	=
NetworkMode	=


[Mode]
DisplayMode	= Normal


[DomeMaster]
BufferSize	= 1024
CaptureSize	= 2048
MeshNum		= 30
ElevationAngle	= 45
ElevationAnglePlanetarium = 30
DomeR		= 200.0
CameraRotationAngle = 0
AmplificationFactor = 4.0
LineWidthFactor = 2.5
LabelSizeFactor = 2.0
ProjOffsetX	= 0.0
ProjOffsetY	= 0.0
ProjOffsetZ	= 0.0
ProjElevAngle	= 90.0
ProjAzimuth	= 0.0
ProjSlue	= 0.0
ProjViewAngle	= 180.0
UseDomeIntersection = 0
IntersectionElevAngle = 90
IntersectionAzimuth = 0
ShiftX	= 0.0
ShiftY	= 0.0


[CaptureCubeMap]
CaptureSize	= 2048
AmplificationFactor = 1.0
LineWidthFactor	= 1.0
LabelSizeFactor = 1.0
Coordinates	= LocalCamera


[Movie]
Renderer	= EVR
;Renderer	= Windowed
FadingDuration	= 1.0


[Date]
DispDuration = 1.0
FadeDuration = 0.5
InputPause   = 0.2
PosY	= 0


[Performance]
Speed			= 1.0
GalaxyRayNum		= 7000
GalaxyRayStepLength	= 40
GalaxyStarNum		= 5000
TextureReduction	= 1
DistantGalaxyThinning	= 0
EnableDrawLowRes	= 0
EnableChangeViewAnimation = 0
ChangeViewAnimationSpeed = 1.0


[Display]
MagFactor	= 1


[Mouse]
ZoomReverse	= 0
HideTimeout	= 3.0


[Joystick]
Enable		= 1
TimerInterval	= 5
AXIS_X		= 0
AXIS_Y		= 1

;--- Default
AXIS_RZ		= 2
AXIS_Z		= 3
;--- ELECOM JC-U4113S
;AXIS_RZ	= 3
;AXIS_Z		= 2

;--- Sony PS2 (Default)
BTN_TRI		= 0
BTN_CIR		= 1
BTN_CRS		= 2
BTN_SQR		= 3
BTN_L2		= 4
BTN_R2		= 5
BTN_L1		= 6
BTN_R1		= 7
BTN_START	= 8
BTN_SELECT	= 9
;---------------------

;--- ELECOM JC-U3412S
;BTN_TRI = 1
;BTN_CIR = 3
;BTN_CRS = 2
;BTN_SQR = 0
;BTN_L2 = 6
;BTN_R2 = 7
;BTN_L1 = 4
;BTN_R1 = 5
;BTN_START = 9
;BTN_SELECT = 8
;---------------------

;--- ELECOM JC-U4113S
;BTN_TRI = 1
;BTN_CIR = 3
;BTN_CRS = 2
;BTN_SQR = 0
;BTN_L2 = 6
;BTN_R2 = 7
;BTN_L1 = 4
;BTN_R1 = 5
;BTN_START = 11
;BTN_SELECT = 10

;--- Logicool F710 / Logicol F510/ Logicool F310 / Logitech Rumble Pad 2
;BTN_TRI = 3
;BTN_CIR = 2
;BTN_CRS = 1
;BTN_SQR = 0
;BTN_L2 = 6
;BTN_R2 = 7
;BTN_L1 = 4
;BTN_R1 = 5
;BTN_START = 9
;BTN_SELECT = 8
;---------------------

;--- Default
BTN_L3		= 10
BTN_R3		= 11
;--- ELECOM JC-U4113S
;BTN_L3		= 8
;BTN_R3		= 9

BTN_UP		= 12
BTN_RIGHT	= 13
BTN_DOWN	= 14
BTN_LEFT	= 15
PowerIndex	= 1.0


[Inertia]
TrackballMass			= 2.0
TrackballFriction		= 2.0
PlntTrackballMass		= 2.0
PlntTrackballFriction		= 8.0
ZoomLeverMass			= 2.0
ZoomLeverFriction		= 10.0


[Lighting]
Ambient		= 0.0


[PointSize]
MinorPlanets	= 1.0
TNOs		= 1.0
OurGalaxyStars	= 1.0
NearbyGalaxies	= 1.0
DistantGalaxies	= 1.0
QSOs		= 1.0


[PlanetariumMode]
DirectionAltitude = -3.0


[Earth]
Specular			= 6.0
Shininess			= 60.0
AtmosphereIntensity		= 6.0
AtmosphereIntensityPlanetarium	= 20.0


[Sun]
GlareSize	= 5


[Star]
ImagePowIndex	= 0.27
Brightness	= 1.6
MaxVmag		= 13.0


[MilkyWay]
Brightness1	= 1.0
Brightness2	= 8.0
ColorFactorR	= 1.0
ColorFactorG	= 1.0
ColorFactorB	= 1.0
H_AlphaBrightness1= 1.0
H_AlphaBrightness2= 1.5


[CMB]
Brightness	= 0.4
FadeR1		= 0.85
FadeR2		= 1.15


[Title]
TitleDuration	= 0.6
TitleZPosIni	= 0.1


[CreditRoll]
Width		= 180
DY		= -80
Duration	= 3
Angle		= 0


[ObjectInfo]
Size		= 1.1


[Font]
Size		= 1.4
BmpSize		= 1024
CharPixelSize	= 64


[4D2U_Logo]
Size = 1.0
Margin = 0.5
Position = UL


[OnScreenCredits]
Size = 1.0
Margin = 0.5
Position = DR


[Color]
NameObject		= #00BFFF
NameSpecialObject	= #FFFFDD
NameSatellite		= #F0E68C
NameDwarfPlanet		= #D8BFD8
NameSmallObject		= #98FB98
NameInterstellarObject	= #DD7777
NameSpacecraft		= #A6A6B3
AxisPlanet		= #CC9933
PointerPlanet		= #00FF00
OrbitPlanet		= #4682B4
OrbitSatellite		= #8C916A
OrbitDwarfPlanet	= #6666CB
OrbitSmallObject	= #008B8B
OrbitInterstellarObject	= #880000
OrbitStar		= #4682B4
ObjectNameSize		= 2.8
SpecialObjectNameSize	= 3.8
SatelliteNameSize	= 2.5
DwarfPlanetNameSize	= 2.6
SmallObjectNameSize	= 2.4
LocationNameSize	= 3.0
StarMarkBinary		= #FF9999
StarMarkExoplanet1	= #FFE600
StarMarkExoplanet2	= #FF8000
ConstellationName	= #AED75B
ConstellationNameSize	= 2.6
ConstellationLine	= #778899
ConstellationLineWidth	= 1.0
ConstellationIllust	= #1A6699
ConstellationIllustWidth = 1.0
ConstellationBoundary	= #434D56
ConstellationBoundaryWidth	= 1.0
Asterism		= #00A59F
AsterismName		= #00A59F
AsterismLineWidth	= 1.0
Scale			= #EB7847
ScaleText		= #EBBE47
ScaleSquare		= #EB7847
ScaleSquareText		= #EBBE47
ScaleTextSize		= 2.6
ScaleWidth		= 1.4
OrbitWidth		= 1.2
Oort			= #87CEEB
NearbyGalaxiesPoint	= #E6E6E6
QSO			= #5099DE
SunGlare		= #FFF2EE
GridCelestial		= #806666CD
GridGalactic		= #00B39AE6
GridEclipticPlnt	= #FFFF00
GridEclipticSpace	= #FFFF00
HorizonCoord		= #00B3E6CC
DirectionLetter		= #999980FF

MenuText		= #A59FA5
MenuSelect		= #DEDED3
MenuTitle		= #EBBE47
MenuBackground1		= #464E64
MenuBackground2		= #000000
MenuBorder		= #3E4557
MenuHighlight1		= #599AE5
MenuHighlight2		= #2764D2

Blackout		= #000000
4D2U_Logo		= #FFFFFF
4D2U_LogoAlpha		= 0.5
OnScreenCredits		= #FFFFFF
OnScreenCreditsAlpha	= 0.5
Date			= #BCE9D0
DateRealTime		= #F3CDB1
DateAlpha		= 0.5
DateSize		= 0.9


[Menu]
Visible		= 1
SystemMenu	= 1
PosAngle	= 0
RotateAngle	= 0
TextSize	= 0.7
CornerR		= 0.5
BgAlpha		= 0.95
BdWidth		= 1.0
BehindAlpha	= 0.4
FadingRate	= 3
FadingDuration	= 0.15
TriangleDy	= -0.08
